// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Badge {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  description?: string;
  min_lots?: number;
  icon_url?: string;
  color?: string;
  emoji?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Broker {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  description?: string;
  logo_url?: string;
  website?: string;
  affiliate_url?: string;
  broker_status?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Comment {
  id: string;
  slug: string | null;
  status: string;
  target_id: string;
  target_type: string;
  content: string;
  parent_id?: string;
  is_deleted?: boolean;
  user_id?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  user_id?: string;
  content: string;
  visibility?: string;
  like_count?: number;
  comment_count?: number;
  view_count?: number;
  instrument_id?: string;
  images?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Course {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  excerpt?: string;
  description?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: unknown;
  category_id?: string;
  prerequisite_id?: string;
  access_level?: string;
  is_purchasable?: boolean;
  required_plan_ids?: unknown;
  price?: number;
  currency?: string;
  sale_price?: number;
  sale_start?: string;
  sale_end?: string;
  duration_hours?: number;
  difficulty?: string;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Deal {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  user_id?: string;
  broker_id?: string;
  deal_ticket?: string;
  symbol?: string;
  deal_type?: string;
  volume?: number;
  price?: number;
  profit?: number;
  commission?: number;
  swap?: number;
  deal_time?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Enrollment {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  user_id?: string;
  course_id?: string;
  source?: string;
  order_id?: string;
  enrollment_status?: string;
  progress?: number;
  started_at?: string;
  completed_at?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Follow {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  follower_id: string;
  following_id: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Industry {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  sector_id?: string;
  description?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Instrument {
  id: string;
  slug: string | null;
  status: string;
  symbol?: string;
  name?: string;
  asset_class?: string;
  sector_id?: string;
  industry_id?: string;
  description?: string;
  logo_url?: string;
  instrument_status?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Lesson {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  module_id?: string;
  course_id?: string;
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: unknown;
  summary?: unknown;
  video_url?: string;
  duration_minutes?: number;
  sort_order?: number;
  is_preview?: boolean;
  prerequisite_id?: string;
  complexity?: string;
  resources?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Plan {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  description?: string;
  price_usd?: number;
  duration_days?: number;
  features?: unknown;
  plan_status?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Membership {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  user_id?: string;
  plan_id?: string;
  start_date?: string;
  end_date?: string;
  membership_status?: string;
  order_id?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface MissionType {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  description?: string;
  reward_lots?: number;
  daily_limit?: number;
  category?: string;
  icon?: string;
  mission_status?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Module {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  course_id?: string;
  description?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Notification {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  recipient_id: string;
  actor_id?: string;
  type: string;
  target_id?: string;
  target_type?: string;
  preview?: string;
  is_read?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Order {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  user_id?: string;
  order_type?: string;
  item_id?: string;
  subtotal?: number;
  discount_amount?: number;
  amount?: number;
  currency?: string;
  coupon_id?: string;
  coupon_code?: string;
  order_status?: string;
  payment_provider?: string;
  payment_id?: string;
  metadata?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Position {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  user_id?: string;
  broker_id?: string;
  symbol?: string;
  direction?: string;
  volume?: number;
  open_price?: number;
  current_price?: number;
  sl?: number;
  tp?: number;
  profit?: number;
  opened_at?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Position {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  user_id?: string;
  broker_id?: string;
  symbol?: string;
  direction?: string;
  volume?: number;
  open_price?: number;
  close_price?: number;
  profit?: number;
  opened_at?: string;
  closed_at?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Sector {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  description?: string;
  icon?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    badges: Badge;
    brokers: Broker;
    community_comments: Comment;
    community_posts: Post;
    courses: Course;
    deals: Deal;
    enrollments: Enrollment;
    follows: Follow;
    industries: Industry;
    instruments: Instrument;
    lessons: Lesson;
    membership_plans: Plan;
    memberships: Membership;
    mission_types: MissionType;
    modules: Module;
    notifications: Notification;
    orders: Order;
    pages: Page;
    positions_active: Position;
    positions_closed: Position;
    posts: Post;
    sectors: Sector;
  }
}